# Generated by Django 5.0.6 on 2024-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_remove_product_product_id_alter_product_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(),
        ),
    ]
